checkpoints:
  checkpoint_interval: 500
  checkpoints_path: checkpoints-opcansf-opencoder
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: checkpoints-opcansf-opencoder
  save_initial_state: false
  save_final_state: true

data_stages:
- data:
    dataset:
      dataset_folder: /home/aiops/zhuty/cont_data/opcansf/tokenized/data
      tokenizer_name: tyzhu/opencoder484
      vocab_size: 96541
      token_size_in_bytes: 4
    num_loading_workers: 2
    seed: 42
  name: opcansf
  start_training_step: 1

general:
  project: nano-cont
  run: opcansf-opencoder484-continual
  seed: 42
  ignore_sanity_checks: true

logging:
  log_level: info
  log_level_replica: info
  iteration_step_info_interval: 1

model:
  dtype: bfloat16
  ddp_bucket_cap_mb: 25
  make_vocab_size_divisible_by: 128
  init_method:
    path: /home/aiops/zhuty/nanotron/nanotron_models/opencoder484
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 2240
    initializer_range: 0.02
    intermediate_size: 6144
    is_qwen2_config: true
    max_position_embeddings: 4096
    num_attention_heads: 14
    num_hidden_layers: 24
    num_key_value_heads: 14
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    rope_theta: 10000.0
    rope_interleaved: false
    rope_seq_len_interpolation_factor: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 96541
    _attn_implementation: flash_attention_2
    flex_attention_mask: null
    attention_bias: false
    sliding_window_size: null
    z_loss_enabled: false
    z_loss_coefficient: 0.0001
    no_rope_layer: null
    _fused_rotary_emb: true
    _fused_rms_norm: true
    _use_qkv_packed: true
    _use_doc_masking: false
    log_attn_probs: false
    ring_attn_heads_k_stride: null
    moe_config: null

optimizer:
  accumulate_grad_in_fp32: false
  clip_grad: 1.0
  weight_decay: 0.1
  optimizer_factory:
    name: adamW
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    torch_adam_is_fused: true
  learning_rate_scheduler:
    learning_rate: 5.0e-05
    lr_warmup_steps: 100
    lr_warmup_style: linear
    lr_decay_style: linear
    lr_decay_steps: null
    lr_decay_starting_step: 10000
    min_decay_lr: 5.0e-06
  zero_stage: 1

parallelism:
  dp: 8
  tp: 1
  pp: 1
  pp_engine: 1f1b
  expert_parallel_size: 1
  tp_mode: REDUCE_SCATTER
  tp_linear_async_communication: true
  tp_recompute_allgather: false
  context_parallel_size: 1
  recompute_layer: true

profiler: null

tokenizer:
  tokenizer_name_or_path: tyzhu/opencoder484
  tokenizer_revision: null
  tokenizer_max_length: null

tokens:
  sequence_length: 4096
  micro_batch_size: 1
  batch_accumulation_per_replica: 128
  train_steps: 10000
  val_check_interval: -1
  limit_val_batches: 0
  limit_test_batches: 0
